spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_vue?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dyt123

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
